from ..models import Animal
import datetime

ANIMAL_SEEDS = (
    Animal(
        id=1_002_000,
        name="Rex",
        species=Animal.AnimalType.DOG,
        date_of_birth=datetime.date(2019, 1, 1),
        description="Former police dog.",
        intake_date=datetime.date(2023, 11, 1),
    ),
    Animal(
        id=1_002_001,
        name="Jambo",
        species=Animal.AnimalType.CAT,
        date_of_birth=datetime.date(2020, 6, 15),
        description="Orange cat, what more needs to be said.",
        intake_date=datetime.date(2023, 10, 20),
    ),
    Animal(
        id=1_002_002,
        name="Hopper",
        species=Animal.AnimalType.RABBIT,
        date_of_birth=datetime.date(2021, 3, 10),
        description="Friendly rabbit with soft white fur.",
        intake_date=datetime.date(2023, 9, 15),
    ),
    Animal(
        id=1_002_003,
        name="Shadow",
        species=Animal.AnimalType.DOG,
        date_of_birth=datetime.date(2018, 12, 25),
        description="Calm and loyal German Shepherd mix.",
        intake_date=datetime.date(2023, 8, 10),
    ),
    Animal(
        id=1_002_004,
        name="Mittens",
        species=Animal.AnimalType.CAT,
        date_of_birth=datetime.date(2021, 11, 5),
        description="Shy but affectionate Persian cat.",
        intake_date=datetime.date(2023, 7, 5),
    ),
    Animal(
        id=1_002_005,
        name="Bunny",
        species=Animal.AnimalType.RABBIT,
        date_of_birth=datetime.date(2022, 4, 2),
        description="Active rabbit who loves to explore.",
        intake_date=datetime.date(2023, 6, 18),
    ),
    Animal(
        id=1_002_006,
        name="Patches",
        species=Animal.AnimalType.CAT,
        date_of_birth=datetime.date(2019, 9, 8),
        description="Calico cat with a distinctive coat pattern.",
        intake_date=datetime.date(2023, 5, 25),
    ),
    Animal(
        id=1_002_007,
        name="Bolt",
        species=Animal.AnimalType.DOG,
        date_of_birth=datetime.date(2020, 2, 14),
        description="Energetic Jack Russell Terrier mix.",
        intake_date=datetime.date(2023, 4, 10),
    ),
    Animal(
        id=1_002_008,
        name="Nibbles",
        species=Animal.AnimalType.RABBIT,
        date_of_birth=datetime.date(2021, 8, 22),
        description="Gentle rabbit with light brown fur.",
        intake_date=datetime.date(2023, 3, 5),
    ),
)
